// <auto-generated />
namespace AnimalAdoptionWebsite_FinalYearProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ChangedAnimalStringlengthsfrom200to500 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangedAnimalStringlengthsfrom200to500));
        
        string IMigrationMetadata.Id
        {
            get { return "202103281613556_Changed-Animal-Stringlengths-from-200-to-500"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
