// <auto-generated />
namespace AnimalAdoptionWebsite_FinalYearProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ChangedIsAvailabletoIsUnavailableinAnimal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangedIsAvailabletoIsUnavailableinAnimal));
        
        string IMigrationMetadata.Id
        {
            get { return "202104181227397_Changed-IsAvailable-to-IsUnavailable-in-Animal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
